### ISSUE TITLE
NVIDIA Jetson Nano Case Build

### ISSUE THREAD

**Issue by florianporada** [opendatacam/opendatacam#101]
### Instructions

**Here are some steps to set up the Jetson NANO in the [Wildlife Cam Casing from Naturebytes](http://naturebytes.org/our-tech/).**

![IMG_20190529_100541](https://user-images.githubusercontent.com/10535875/60716891-c1c20a80-9f20-11e9-99cc-0e1b3ce691e7.jpg)

The casing is originally designed for the raspberry pi 3. The good thing is, that the form-factor of the nano board is not that different so with some simple modifications of the base plate, the Jetson board will fit in this rather cheap casing.

![IMG_0441](https://user-images.githubusercontent.com/10535875/60716838-a9ea8680-9f20-11e9-9048-241556674fb9.png)

In the above picture you can see the hand drilled holes (marked in red) and the existing one (marked in blue)

![IMG_0440](https://user-images.githubusercontent.com/10535875/60716416-a3a7da80-9f1f-11e9-9bc1-b71713b787de.png)

The easiest way to fit the board on the baseplate is to fix it with one thread screw on the existing hole and rotate the board to the point where it fits perfectly on the baseplate. Make sure to leave some space for the power adapter since it takes a bit of space. ([Link to the adapter](https://www.amazon.de/gp/product/B004US2XPS/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1))

Once it fits mark the spots for the hole and drill it with an electric drill (preferably with an 3mm bit since the screws used are M3s)

Reference with marked hand-drilled holes (red):

![IMG_0445](https://user-images.githubusercontent.com/10535875/60716799-94755c80-9f20-11e9-8c1e-0c8d5bfaf96d.png)
![IMG_0446](https://user-images.githubusercontent.com/10535875/60716800-94755c80-9f20-11e9-9708-460027f55dba.png)
![IMG_0447](https://user-images.githubusercontent.com/10535875/60716801-94755c80-9f20-11e9-8929-b0eac686b3c5.png)

When installing the RaspiCam make sure to cover the screws with some electrical tape to prevent short circuits since the board will be mounted on the other side of the plate.

![IMG_0442](https://user-images.githubusercontent.com/10535875/60716988-02218880-9f21-11e9-9bd9-64ddf4793bf4.png)

Front:
![IMG_0448](https://user-images.githubusercontent.com/10535875/60717400-f5e9fb00-9f21-11e9-8ec6-79721edbfdc7.png)

Back: 
![IMG_0449](https://user-images.githubusercontent.com/10535875/60717440-14e88d00-9f22-11e9-95a0-d4afcf73030b.png)

(cc @b-g , @tdurand )

**Comment by rraapphhaaeell** [comment]
Awesome docs @florianporada - we should add this to the wiki. I'll also add other ways to build an ODC - feel free to share yours.

**Comment by tdurand** [comment]
Great ! Yes feel free to add a markdown file in the /documentation/jetson section: https://github.com/opendatacam/opendatacam/tree/master/documentation/jetson and link it somewhere ;-) .

**Comment by tdurand** [comment]
Maybe we can add a "enclosure" folder and create one per Jetson ?

**Comment by rraapphhaaeell** [comment]
> Maybe we can add a "enclosure" folder and create one per Jetson ?

yes, also a shopping list per setup would be nice, and a good (in depth) link for the website section on the different models.

**Comment by tdurand** [comment]
Yep, I already added shopping list Information for the jetson nano: https://github.com/opendatacam/opendatacam/blob/master/documentation/jetson/JETSON_NANO.md#shopping-list . 

Next week I can create one for TX2 and one for Xavier even if it will be more limited as most of what you need comes with the developer kit.

Also this ressource is really nice: https://elinux.org/Jetson_Nano, https://elinux.org/Jetson_TX2, https://elinux.org/Jetson_AGX_Xavier ... It lists compatible cameras, cases etc etc ...

It might make sense to contribute this enclosure to this wiki also.

**Comment by b-g** [comment]
@florianporada Thanks! What about scanning the base plate (think of Kopierer) so that you can print it out and simply mark the custom holes? Then you don't have to fiddle around with a ruler and it will be much quicker ...

**Comment by florianporada** [comment]
@b-g . This is a good idea! The pictures with the ruler where meant more for an overview.
My initial thought was, that the build included the 'rotation-technique' 😃 .. but I will include the scan of the baseplate.

**Comment by florianporada** [comment]
https://opendatacam.github.io/opendatacam/documentation/jetson/HOUSING.html

Further thoughts @b-g , @rraapphhaaeell ? 

otherwise feel free to close this issue

**Comment by b-g** [comment]
@florianporada Just checked it. Mega nice documentation to get a nice housing for the Nano! Great! 👏

**Comment by b-g** [comment]
Done! Closed with https://github.com/opendatacam/opendatacam/blob/master/documentation/jetson/HOUSING.md
