### ISSUE TITLE
Memory usage increases gradually on Jetson-nano

### ISSUE THREAD

**Issue by anasBahou** [opendatacam/opendatacam#108]
Hello everyone, i'm having an issue with memory usage in Jetson-nano.
I'm using ODC without docker with rasberry Pi camera Module v2 and yolov3-tiny.
Once I start ODC, my memory usage increases gradually till saturation. 
![Screenshot from 2019-07-15 11-19-10](https://user-images.githubusercontent.com/36683886/61206763-a9f23f80-a6f3-11e9-8fb0-ab7b6d1bc86e.png)
 
Any idea how to resolve this.

**Comment by tdurand** [comment]
Hi ! Yes, this is a know issue, please continue the discussion here: https://github.com/opendatacam/opendatacam/issues/95
