### ISSUE TITLE
ALPR on opendatacam

### ISSUE THREAD

**Issue by arnoldhoward** [opendatacam/opendatacam#110]
I gonna implement ALPR on opendatacam. 
I saw this issue . 
https://github.com/opendatacam/opendatacam/issues/63
I have a different idea with this. 
I'd like to know how can i change the detection part...
Thanks.

**Comment by tdurand** [comment]
Hi, please refer to the technical architecture documentation for help to understand opendatacam code source: https://github.com/opendatacam/opendatacam/blob/master/documentation/DEVELOPMENT_NOTES.md#technical-architecture

Let us know how it goes for you... We aren't working on this now, but we will update future progress on #63
