### ISSUE TITLE
start Opendatacam without waiting for the first detection

### ISSUE THREAD

**Issue by anasBahou** [opendatacam/opendatacam#115]
Hi, 

How can we start Opendatacam without waiting for the first detection??

Thanks.

**Comment by tdurand** [comment]
Those two pointers might help you:

- We only start the darknet process when we have a first HTTP request: https://github.com/opendatacam/opendatacam/blob/master/server.js#L101  , if you want to start the darknet process before, just move what is inside this handler outside.. But you will maybe need to hardcode "localhost" in the listenToYOLO funcion in Opendatacam.. Not sure the best way to go..  We had some this for simplicity, and also only starting Opendatacam when people are actually using it... but it can be much improved

- We send process the darknet message and stream data over the SSE socket only if the message received by the darknet process is complete: https://github.com/opendatacam/opendatacam/blob/master/server/Opendatacam.js#L534 

Happy to give more insights if needed
