### ISSUE TITLE
Expose confidence level in Tracker data 

### ISSUE THREAD

**Issue by b-g** [opendatacam/opendatacam#129]
Currently tracker data is:

`{"id":166,"x":1130,"y":564,"w":139,"h":212,"bearing":255,"name":"car"}`

Just realized that we don't expose the confidence level in the tracker data. Would be nice to have it as well.

**Comment by tdurand** [comment]
Good catch, I thought it was there.. I fixed that, will do another build release with it later today

https://github.com/opendatacam/opendatacam/commit/2a3145365603f510cf5a37fd013be72ac64123d5

**Comment by b-g** [comment]
@tdurand Should we not map it to 0 to 100? We are mapping all the raw yolo data to int ... just not this one.

**Comment by tdurand** [comment]
ok, yes let's be coherent ;-)
