### ISSUE TITLE
I want try you project.

### ISSUE THREAD

**Issue by meatpush** [opendatacam/opendatacam#132]
Hello. My name is Ivan Borovskoy,I am 14 years old and I want try your program for my project. But I am only studying and don't know how your project work. Can you explain or give some tips about your project.The project "Smart city" is developing in my city and I was asked to participate in it. But since I am just learning, I have problems with the implementation of the project. So I was looking for similar projects and found your project. And I'd like to use it. Advance thanks.

**Comment by b-g** [comment]
Thank for the interest!

Please see and check:
https://opendata.cam
https://github.com/opendatacam/opendatacam/blob/master/README.md
