### ISSUE TITLE
How to export data

### ISSUE THREAD

**Issue by ItelBz** [opendatacam/opendatacam#137]
Hi,
I have multiple reading points so I want to export the tracking data into an external website to have all in one place.
My idea was to insert a box like the one present in the Data section.

My site is based on Nodejs and react.

![image](https://user-images.githubusercontent.com/55224997/67635433-8c726b80-f8c7-11e9-9f43-cfd032f05737.png)

Any idea?

Thank you!

**Comment by tdurand** [comment]
Hi, 

- You can download the data directly from the data panel
- Or your can use the API to get the data: https://opendatacam.github.io/opendatacam/apidoc

Then if you want inspiration for the styling of your front-end, the code for this is : https://github.com/opendatacam/opendatacam/blob/master/components/dataview/Recording.js

Best, 

Thibault
