### ISSUE TITLE
Total vehicle count (slow traffic) and vehicle in the opposite direction

### ISSUE THREAD

**Issue by linuxfxdevil** [opendatacam/opendatacam#140]
It would be very interesting if we had these features available, since yolo itself can already provide us with the total vehicle count, I believe an alarm warning that the total of pre-defined vehicles was exceeded at that time would be great!

**Comment by tdurand** [comment]
Thanks for you question, some input on how to solve this here: https://github.com/opendatacam/opendatacam/issues/122
