### ISSUE TITLE
Track Object and people Detection

### ISSUE THREAD

**Issue by linuxfxdevil** [opendatacam/opendatacam#141]
It would be great if we had alarm options to warn people and objects on the track. Imagine a scenario where an object or even a person is on the track and the system would inform and record it so that we can later know who and when caused an accident?

**Comment by tdurand** [comment]
Thanks for your input, the API gives you a end point to get the live stream of the objects detected, you could build you custom logic to do some actions depending on this: https://opendatacam.github.io/opendatacam/apidoc/#api-Tracker-Data .
