### ISSUE TITLE
Accuracy rate of tracking algorithm?

### ISSUE THREAD

**Issue by gabbyhan** [opendatacam/opendatacam#159]
Hi,

I am utilizing Open data cam for a research project and I was wondering if you guys had numbers for how accurate the tracking algorithm is given that I have not changed any of the pre-set weights, or tuned anything else. I simply installed data cam as is and ran it on pre-existing footage.

Thanks!

**Comment by tdurand** [comment]
Hi, 

For now we don't, but we have started to work on benchmarking it against the MOT challenge: https://github.com/opendatacam/node-moving-things-tracker/blob/mot/documentation/BENCHMARK.md

The tracker is based on this paper: http://elvera.nue.tu-berlin.de/files/1547Bochinski2018.pdf
