### ISSUE TITLE
Add specific cuda/cudnn tag version to Dockerfile

### ISSUE THREAD

**Issue by b-g** [opendatacam/opendatacam#162]
I'm wondering in terms of long term support whether it would not be better to add the cuda/cdnn version tag to our dockerfiles?

e.g. https://github.com/opendatacam/opendatacam/blob/master/docker/run-nvidia-docker/Dockerfile#L1

`FROM nvidia/cuda`

becomes

`FROM nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04`

as currently it is simply `latest` ...

**Comment by shams3049** [comment]
latest is always with cool new features, but will definitely struggles with stability.  So the question is in long term are you going for stability or features. I personally prefer the latest tag.

**Comment by tdurand** [comment]
Yes, I mean at some point latest might break, and it would prevent it by setting a fixed version... Not sure if we get any perf improvement of having always the latest CUDA.

**Comment by tdurand** [comment]
This will be done with this : https://github.com/opendatacam/opendatacam/issues/178
