### ISSUE TITLE
Quering Data from MongoDB

### ISSUE THREAD

**Issue by rantgithub** [opendatacam/opendatacam#164]
Hi

I have the following question  about getting data from the mongodb.

From the database interface portion, when I click on the CSV link, the CSV file associate with the count is downloaded.

If I want to add additional fields into the CSV field, can you point out please what is the module that I can modify query the mongodb and  include these additional fields into the csv file.

On the same line, is I want to get a limited json file, howI can downlaod a particular query

Thank you

**Comment by tdurand** [comment]
Hi, 

You should modify this: https://github.com/opendatacam/opendatacam/blob/master/server.js#L752 

You should probably create another method in the DBManager querying what you need: https://github.com/opendatacam/opendatacam/blob/master/server/db/DBManager.js 

It is the same for the JSON here: https://github.com/opendatacam/opendatacam/blob/master/server.js#L719
