### ISSUE TITLE
Start recording without recording id possible

### ISSUE THREAD

**Issue by gabkol** [opendatacam/opendatacam#167]
When I run `wget localhost:8080/recording/start` in a cronjob script opendatacam starts the recording without generating a new recording id. The job runs with root privileges.

After that `wget localhost:8080/recording/status` returns recording id is null: `{
    "appState":
    {
        "isListeningToYOLO": true,
        "recordingStatus":
        {
            "currentFPS": 71,
            "dateStarted": "2019-12-12T09:13:42.338Z",
            "filename": "",
            "isRecording": true,
            "recordingId": null,
            "requestedFileRecording": false
        },
        "yoloStatus":
        {
            "isStarted": true,
            "isStarting": false
        }
    },
    "counterSummary":
    {
        "77048b0f-98a9-4698-8be1-8c53f80993a9":
        {
            "_total": 1,
            "bus": 1
        },
        "85ad5410-23df-4273-a3dd-4e5bf71c0255":
        {
            "_total": 4,
            "car": 3,
            "person": 1
        },
        "8708a86e-82ed-4f5a-a041-f7e05badd356":
        {
            "_total": 2,
            "car": 2
        }
    },
    "trackerSummary":
    {
        "totalItemsTracked": 27
    },
    "videoResolution":
    {
        "h": 360,
        "w": 640
    }
}`

It seems impossible to get the data tracked with recording id null.

**Comment by tdurand** [comment]
Hi,

This is weird, maybe a problem connecting to the mongodb, do you have some error in the console ? 

If you want to try to debug, you should put some console.log here: https://github.com/opendatacam/opendatacam/blob/master/server/Opendatacam.js#L478  

When we start to record, we create a new Recording object that gets an id from mongodb
