### ISSUE TITLE
Shopping List, SD Card

### ISSUE THREAD

**Issue by mega-stoffel** [opendatacam/opendatacam#169]
Hej there! I was just browsing through your shopping list on this page:
--> https://opendatacam.github.io/opendatacam/documentation/jetson/JETSON_NANO.html#shopping-list
There you mention a microSD card, with minimum 100MB/s. Is this just the read speed or is it also needed for writing?
Thanks for your great work! :-)

**Comment by tdurand** [comment]
For example this one will do: https://www.amazon.com/Samsung-MicroSDXC-Adapter-MB-ME256GA-AM/dp/B072HRDM55/ref=sr_1_3?keywords=micro+sd+card&qid=1576712576&sr=8-3 

I believe it is 90 MB/s for write
