### ISSUE TITLE
Help in using opendatacam api-Reg

### ISSUE THREAD

**Issue by aswinkumar2019** [opendatacam/opendatacam#171]
Hello guys,
I am new to nodejs.
I tried to use the documentation here (https://opendatacam.github.io/opendatacam/apidoc/) to pull data using http module of nodejs.
I get a lot of error messages.
Anybody please help me in using the api with the help of a sample code.
Regards,
Aswin Kumar

**Comment by tdurand** [comment]
Hi, 

Could you be more specific on what is the error and what are you trying to achieve ? 

Best

**Comment by aswinkumar2019** [comment]
Sorry,i have not used rest api before so,had some issues.
I am able to pull data successfully in python.Thanks a lot
