### ISSUE TITLE
Video shows up only after something is detected

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam#177]
https://github.com/opendatacam/opendatacam/issues/166#issuecomment-588367275

**Comment by tdurand** [comment]
To reproduce: set valid classes in config file to something that isn't in the video, and will be always on the init screen with errors in the console

**Comment by b-g** [comment]
Same for me with v3.0.0-alpha.1 @tdurand

**Comment by tdurand** [comment]
@b-g expected, no fix has been made yet for this

**Comment by tdurand** [comment]
Ok, this should fix it: https://github.com/opendatacam/opendatacam/commit/eda5032c5781839baa27f0e3ba0c2cc0d04e81ac , will close for now and let's re-open if still there when testing next version
