### ISSUE TITLE
Feedback v3.0.0-alpha.1

### ISSUE THREAD

**Issue by b-g** [opendatacam/opendatacam#182]
Is is way better now! It was running fine for days ... see screenshots. Also I can confirm bug #177, definitely a problem on start up and a blocker to use OpenDataCam in the wild.

<img width="1249" alt="Screenshot 2020-03-10 at 15 16 49" src="https://user-images.githubusercontent.com/480224/76746014-1c318d00-6777-11ea-8065-7367930841bb.png">
<img width="1131" alt="Screenshot 2020-03-11 at 08 43 33" src="https://user-images.githubusercontent.com/480224/76746022-205daa80-6777-11ea-9a62-b328332997b7.png">
<img width="1313" alt="Screenshot 2020-03-11 at 13 38 36" src="https://user-images.githubusercontent.com/480224/76746027-218ed780-6777-11ea-8c12-f36cebed05a9.png">
<img width="1348" alt="Screenshot 2020-03-12 at 10 01 26" src="https://user-images.githubusercontent.com/480224/76746030-22c00480-6777-11ea-9bfa-a893677ca818.png">
<img width="1054" alt="Screenshot 2020-03-13 at 10 57 00" src="https://user-images.githubusercontent.com/480224/76746034-23f13180-6777-11ea-86b9-d3d34df55f92.png">

**Comment by tdurand** [comment]
Great news !!

**Comment by rantgithub** [comment]
if you need help with testing V3.0 alpha let me know and i will assign some time to that

**Comment by tdurand** [comment]
@rantgithub thanks, will ping you later this week once I release the next version

**Comment by tdurand** [comment]
New version released: https://github.com/opendatacam/opendatacam/issues/184
