### ISSUE TITLE
supporting Deepstream SDK

### ISSUE THREAD

**Issue by SaddamBInSyed** [opendatacam/opendatacam#201]
Hi all,

thanks for the great work.

Is there any possibility to add deepstream [SDK ](https://developer.nvidia.com/deepstream-download)for jetson device.?
since it can handle and gives good fps for multiple camera's.

thanks.

**Comment by tdurand** [comment]
Hi, 

Thanks, please read: https://github.com/opendatacam/opendatacam/issues/112 , and the current status of this: https://github.com/opendatacam/opendatacam/issues/112#issuecomment-594595524

Conclusion is to stick with darknet cause effort to switch to deepstream is too high regarding the time we can spend on this projet. But there is some work in progress you can use as a start if you need this.

Also we will be monitoring  future version of Deepstream that should be likely easier to integrate to this project.
