### ISSUE TITLE
Error while loading shared libraries: libcudart.so.10.0

### ISSUE THREAD

**Issue by jonnymccullagh** [opendatacam/opendatacam#202]
I'm installing on a Jetson Nano and followed the installation guides but I am now getting this error when viewing localhost:8080

```
./uselib: error while loading shared libraries: libcudart.so.10.0: cannot open shared object file: No such file or directory
Restart YOLO
```
Docker shows:
```
CONTAINER ID        IMAGE                                        COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
a8f7d74051af        opendatacam/opendatacam:v3.0.0-beta.1-nano   "/bin/sh -c ./docker…"   23 hours ago        Up 13 minutes       0.0.0.0:8070->8070/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8090->8090/tcp, 27017/tcp   opendatacam
```
I believe I have the LD_LIBRARY_PATH set (even twice!)
```
echo $LD_LIBRARY_PATH
:/usr/local/cuda/lib64:/usr/local/cuda/lib64
```
and the path to the binaries:
```
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin:/usr/local/cuda/bin
```
The lib64 directory contains the libraries for 10.2 but there was no libcudart.so.10.0   So I also tried adding a symlink in there pointing to the 10.2 version but I still get the error.

```
ls /usr/local/cuda/lib64
libcudadevrt.a                libnppicom.so.10.2.1.89
libcudart.so                  libnppicom_static.a
libcudart.so.10.0             libnppidei.so
libcudart.so.10.2             libnppidei.so.10
libcudart.so.10.2.89          libnppidei.so.10.2.1.89
libcudart_static.a            libnppidei_static.a
libcufft.so                   libnppif.so
libcufft.so.10                libnppif.so.10
```
So I don't know whether I should try re-installing everything from scratch or if I should be using a version other than v3.0.0-beta.1-nano ?
Any assistance is appreciated.

**Comment by tdurand** [comment]
Hi,

Thanks, sorry for the problem. Are you using Jetpack 4.3 or Jetpack 4.4 DP ? Jetpack 4.4 DP might not work . ( [How to find your jetpack version](https://github.com/opendatacam/opendatacam/blob/master/documentation/jetson/FLASH_JETSON.md#how-to-find-out-my-jetpack-version) ) 

Also, I'm gonna publish v3.0.0-beta.2 around next monday/tuesday so I would advise you to wait for it as it will changes lots of dependencies.. but if you really want to tinker before you can also try to install dependencies manually: https://github.com/opendatacam/opendatacam/blob/master/documentation/USE_WITHOUT_DOCKER.md
