### ISSUE TITLE
Error connecting to IP Stream

### ISSUE THREAD

**Issue by andtheWings** [opendatacam/opendatacam#208]
Hi, I am using v3.0.0-beta.2-nvidiadocker on my laptop. I successfully tested it out using a video file. Thought I would try it out with [a random IP Cam in my city](https://www.insecam.org/en/view/468911/) I got on Insecam. I set `"VIDEO_INPUT": "remote_cam"` and `"remote_cam": "http://69.108.44.90:83/"`. When starting up, I got the following error that runs indefinitely:

![error message](https://i.postimg.cc/1tdkxng8/opendatacam-ip-stream-error.png)

**Comment by tdurand** [comment]
You need to get the actual image stream link and not the general interface of the webcam: maybe this one will work: http://69.108.44.90:83/GetData.cgi?CH=1

**Comment by andtheWings** [comment]
I tried the new link and got running messages like this: ![error message](https://i.postimg.cc/v8hNbXYn/Screenshot-from-2020-05-11-15-57-45.png)

**Comment by tdurand** [comment]
hum.. this feed does not seem to be compatible out of the box with OpenCV .

This gstreamer pipeline to decode a MJPEG stream should work:

```souphttpsrc location=http://69.108.44.90:83/GetData.cgi?CH=1 ! multipartdemux ! image/jpeg,width=640,height=480 ! appsink```

But maybe the camera isn't fast enough.. Can't help much more, try to find cameras with low resolution /  fast FPS and direct access to MJPEG stream.

**Comment by andtheWings** [comment]
Ok, thanks for the help!
