### ISSUE TITLE
New version : v3.0.0-beta.3

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam#218]
### Releasing v3.0.0-beta.3 🎉️ , featuring:

- **Complete rewrite of Docker setup / install process** in order to use `docker-compose`
- Update darknet fork once again using the new -dontdraw_bbox flag AlexeyAB kindly added for us : https://github.com/AlexeyAB/darknet/commit/da050367a8b174f751a2c9720195d51a369c4a4a
- Expose tracker config IOU and UNMATCHED FRAME tolerance
- Check if config.json version matches Opendatacam version
- Clean up code for drag& drop feature.. maybe add some UI tweaks like a drop indicator and a specific progress message
- Clean up and improve counter logic code
- Update API docs with new counters attributes
- Add Threshold  to filter out large detections
- Update OpenMojis

### How to test / install

If you were using OpenDataCam before with docker, the setup has changed to use `docker-compose` now for several reasons

- simplify the install process
- provide flexibility for people to add other docker services around opendatacam
- enable people to deploy on IoT cloud platform like Balena
- makes the workflow with Docker lighter, I think to deploy a new version of OpenDataCam it will be much fast now as we don't need to push everything, the base image will not change... also maybe open the door to build from the cloud
- be independant from jetpack version issues .. (right now we have problem with darknet and jetpack 4.4)

We still have a "one command" install process but you need to install docker-compose first, please read: https://github.com/opendatacam/opendatacam#1-software-pre-requisite-

Note that right now the _raspberry pi cam isn't working on the Jetson nano using this new setup_.. we are trying to fix this... and you might run into other issues as this is a significant change from how things worked previously

### Still TODO

- [x] @fabianmoronzirfas added support for env variables: https://github.com/opendatacam/opendatacam/pull/222
- [x] Add counter settings "minAngleWithCountingLine" : https://github.com/opendatacam/opendatacam/blob/development/documentation/CONFIG.md#counter-settings
- [x] Update documentation CONFIG.md as many default changed now.. we run on the demo.mp4 file now.. and file support is via drag & drop to simplify install process
- [x] Update documentation Jetson nano 
- [ ] Try to fix problem with RaspberryPi Cam on jetson nano not working with new docker setup: https://github.com/opendatacam/opendatacam/issues/178
- [x] Document how to run from custom weights with docker (possible now)
- [x] Document gstreamer use and pipelines
- [x] Update Documentation for yolov3-tiny-prn and yolov4 weights
- [ ] Add a "ethics" message
- [ ] Change picture of OpenDataCam with something with the jetson nano and not the tx2 ?

**Comment by willytrueba** [comment]
Hi,

I have a Jetson Nano with Raspberry 2.0 camera, and I have this error when try to execute.

OpenCV(4.1.1) /usr/src/app/opencv-4.1.1/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): nvarguscamerasrc ! video/x-raw(memory:NVMM),width=1280, height=720, framerate=30/1, format=NV12 ! nvvidconv ! video/x-raw, format=BGRx, width=640, height=360 ! videoconvert ! video/x-raw, format=BGR ! appsink in function 'icvExtractPattern'

Any solution to this issue? Thanks !!

**Comment by tdurand** [comment]
Hi @willytrueba , 

We have some issue with the docker container and the Raspberry camera right now that we are trying to fix: https://github.com/opendatacam/opendatacam/issues/178#issuecomment-642043316

Unfortunately to use it you should install OpenDataCam without docker: https://github.com/opendatacam/opendatacam/blob/master/documentation/USE_WITHOUT_DOCKER.md

**Comment by willytrueba** [comment]
Do you have any idea about when can be fixed this issue with Raspberry Camera 2.0?

**Comment by jvlies** [comment]
I installed the beta yesterday and it is running for hours perfectly. Just amazed now how many vehicles drive past our home...
One issue with the usbcam in the configuration file config.json though. I had to change the VIDEO_INPUT_PARAMS for usbcam to '0' to get my webcam running. Using the default with 'v4l2src' did not work, darknet did not react.

**Comment by tdurand** [comment]
@jvlies interesting.. which device are you using, jetson ? 

@willytrueba not sure, but follow #178 for updates ;-)

**Comment by jvlies** [comment]
> @jvlies interesting.. which device are you using, jetson ?
> 
> @willytrueba not sure, but follow #178 for updates ;-)

No, gamepc type of desktop intel i7, RTX 2060 super, Ubuntu 18 bootable persistant USB, very old Logitech webcam...

**Comment by tdurand** [comment]
@jvlies if you try this command does it work ? v4l2-ctl --list-formats-ext  ?? Maybe you need to `sudo apt-get install -y v4l-utils`

**Comment by jvlies** [comment]
Yes I can execute v4l2-ctl. I made an error with my previous post. I did not use '0' but '-c'.And that works, as I indicated.Now running couple of days 12 hours non-stop.
    On Tuesday, 23 June 2020, 20:45:53 CEST, Thibault Durand <notifications@github.com> wrote:  
 
 


@jvlies if you try this command does it work ? v4l2-ctl --list-formats-ext ?? Maybe you need to sudo apt-get install -y v4l-utils

**Comment by Denizzje** [comment]
Better late than never ;).

* Docker compose install works flawlessly. 
* I am on the development branch I think for the non docker install and it works perfect on Jetpack 4.4 as that is where my Xavier NX came with. So you either fixed the issues or it is Nano only.
