### ISSUE TITLE
Missing requirement on Ubuntu 20.04

### ISSUE THREAD

**Issue by luiscosio** [opendatacam/opendatacam#220]
Hello!

After following the INSTALL instructions, I was getting this error under Ubuntu 20.04:

`ERROR: for opendatacam  Cannot start service opendatacam: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/b81f53a0d8b3432f166d2b48d78b8571e61f8adabde984aa22e62e2e08fdf364/log.json: no such file or directory): fork/exec /usr/bin/nvidia-container-runtime: no such file or directory: unknown`

It is easily fixed by running:

`sudo apt install nvidia-container-runtime`

**Comment by tdurand** [comment]
thanks. just added it: https://github.com/opendatacam/opendatacam/commit/43abc1c51553eab66aabb5b7799ce00f9daadf67
