### ISSUE TITLE
Hi how can I use opendatacam to identify accidents in real time in a live cam feed

### ISSUE THREAD

**Issue by adnansandhila** [opendatacam/opendatacam#229]
Hi how can I use opendatacam to identify accidents in real time in a live cam feed

Thank you
adnan

**Comment by shams3049** [comment]
To my knowledge Yolo will never understand context, it does learn more about the object in context though.

This kind of problem will fall under a complete different class of ML architectures: [For example](https://machinelearningmastery.com/how-to-caption-photos-with-deep-learning/) learning to describe the images to text and then using text to identify accidents.

**Comment by luiscosio** [comment]
@adnansandhila You are probably looking at something like this collision detection for OpenVino:

https://github.com/incluit/OpenVino-For-SmartCity

**Comment by tdurand** [comment]
Yes, OpenDataCam isn't able to detect accidents , thanks for the pointers @shams3049 @luiscosio

**Comment by adnansandhila** [comment]
Thank you everyone specially @luiscosio
