### ISSUE TITLE
YOLOv4 tiny released

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam#231]
I guess I'm up to generate v3.0.1  builds ;-)

https://github.com/AlexeyAB/darknet/issues/6067

**Comment by Denizzje** [comment]
Would it be possible for you to make non Docker version with v4 tiny support too?

**Comment by tdurand** [comment]
What do you mean ? 

I should be able to use tiny-yolov4 already now by following this doc:  https://github.com/opendatacam/opendatacam/blob/master/documentation/CONFIG.md#use-custom-neural-network-weights

Right now the default is yolov3-tiny-prn for Jetson nano, I need to redo the builds to have tinyyolov4 as a default

**Comment by Denizzje** [comment]
Ah, nice. Thought you had to do an update for ODC to make it work with the new tiny model, like updating the darknet used or something. 

Seems I have something to do this weekend ;).

**Comment by tdurand** [comment]
I don't think we need to update darknet code, but I will definitely need to update darknet to include the new tiny yolo .cfg file

**Comment by tdurand** [comment]
> Seems I have something to do this weekend ;).

yes, I've spent half a day to generate and tag the final v3.0.0 yesterday and need to do it again ... update the docs ... bad timing...

**Comment by Denizzje** [comment]
If I have a moment tomorrow I can check if it works already for non Docker ODC on Xavier NX if nessecary.

**Comment by tdurand** [comment]
I just need to  double check the accuracy / speed from yolov3-tiny-prn .. it seems a little bit slower, but score 7% more on the accuracy from the benchmark .. of course welcome to give feedback

**Comment by tdurand** [comment]
Just did all the builds again and made yolov4-tiny default for jetson nano build : https://github.com/opendatacam/opendatacam/releases/tag/v3.0.1

You should update your darknet to make it work if you didn't install with docker

Yolov4-tiny is very impressive in accuracy ...
