### ISSUE TITLE
Default counting line color if we add more than colors defined

### ISSUE THREAD

**Issue by shams3049** [opendatacam/opendatacam#239]
![Screenshot from 2020-07-14 14-33-25](https://user-images.githubusercontent.com/4646205/87427848-aed92000-c5e1-11ea-98b9-f4e3066ee5e0.png)
When the line color is black, its hard to see the directional arrow (black on black). I think the easy fix is not to have black lines.

**Comment by tdurand** [comment]
Hi.. thanks, very minor but keep it on the backlog... the fix will be to just change the default from black to some other color

I'm sure you know you can add more counting lines colors in the config.json: https://github.com/opendatacam/opendatacam/blob/master/documentation/CONFIG.md#customize-counter-colors

**Comment by vsaw** [comment]
Fixed in development. See also https://github.com/opendatacam/opendatacam/pull/498
