### ISSUE TITLE
Installation of the dev branch

### ISSUE THREAD

**Issue by MBelkhechine** [opendatacam/opendatacam#251]
Hi all,

is there a way of installing the dev branch using docker-compose?

Thank you in advance :)

Regards,
Mohamed

**Comment by vsaw** [comment]
As far as I know there's no ready-made docker image for the development branch. You would have to build your own docker image from source.

**Comment by tdurand** [comment]
you would need to build your own docker image,.. those notes can help: https://github.com/opendatacam/opendatacam/blob/master/documentation/jetson/CREATE_DOCKER_IMAGE_JETSON.md
