### ISSUE TITLE
IMX219 - Issues

### ISSUE THREAD

**Issue by Cybersloth** [opendatacam/opendatacam#265]
Hopping someone can help me , this may not be an issue with the software it may be PICNIC (Problem In Chair Not in Computer !)

I have a IMX219 camera with Jetson Nano, I can display video using ...

`gst-launch-1.0 nvarguscamerasrc ! 'video/x-raw(memory:NVMM),width=3820, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=0 ! 'video/x-raw,width=960, height=616' ! nvvidconv ! nvegltransform ! nveglglessink -e`

........etc no problem, I can change the modes and resolution etc

I also have a fully working OpenDataCam install on the Nano (I can use file, usb, rtsp, etc etc no problem.)

BUT I cant use the IMX219 at all in OpenDataCam, depending on the parameters I set I get a host of different errors
The parameters i'm using are variation of ...

`"raspberry": "nvarguscamerasrc ! video/x-raw(memory:NVMM), width=1920, height=1080, framerate=30/1, format=NV12 ! nvvidconv ! video/x-raw, width=960, height=540 ! videoconvert ! video/x-raw, format=BGR ! appsink",`

I think this is the root of the problem....Error opening bin: no element "nvarguscamerasrc"

Any help or pointers appreciated, i have trawled all the usual sources with no success

**Comment by vsaw** [comment]
Are you running the docker image? If so then you are out of luck for now. See the section about the raspicam for more info https://github.com/opendatacam/opendatacam/blob/master/documentation/CONFIG.md

**Comment by Cybersloth** [comment]
Valentin

Many thanks for your response, I had missed this text. I’ll do a full non docker install and try again

Thanks

**Comment by tdurand** [comment]
Yes, access to raspberry pi cam from the docker install does not work.. follow https://github.com/opendatacam/opendatacam/issues/178 for potential updates
