### ISSUE TITLE
Display Object Classification and Logging Issue

### ISSUE THREAD

**Issue by JCrossman** [opendatacam/opendatacam#266]
Has anyone else noticed classifications logged into the database not matching what is being shown on screen? I have a case where the live counter shows a count of 6 cars but when I look in the database it shows 5 cars and 1 horse. I've attached screenshots.
<img width="329" alt="Screen Shot 2020-08-25 at 9 36 21 AM" src="https://user-images.githubusercontent.com/17728252/91196153-037abb00-e6b7-11ea-8f7b-9a9d746e1755.png">
<img width="1206" alt="Screen Shot 2020-08-25 at 9 36 06 AM" src="https://user-images.githubusercontent.com/17728252/91196188-0d042300-e6b7-11ea-95cb-1f8d7c5a9233.png">

**Comment by tdurand** [comment]
closing this as no one reported the same problem.. but feel free to re-open with a procedure to reproduce the bug
