### ISSUE TITLE
Bump node-moving-things-tracker to v0.8.0

### ISSUE THREAD

**Issue by vsaw** [opendatacam/opendatacam#269]
A new version of [node-moving-things-tracker](https://github.com/opendatacam/node-moving-things-tracker) has been released. OpenDataCam needs to be updated to

- use v0.8.0
- allow the new `fastDelete` option in it's config file

See also https://github.com/opendatacam/node-moving-things-tracker/releases/tag/v0.8.0

**Comment by tdurand** [comment]
great ! thanks !
