### ISSUE TITLE
[Question] Hardware suggestion

### ISSUE THREAD

**Issue by Chaaaaaaaaarlie** [opendatacam/opendatacam#271]
I am currently planning to evaluate several locations (each of which has a 24h recording cut into 24 videos). Which hardware would you recommend for 720x480/30FPS videos? On my RTX 2080 it works with ~68FPS, but I want to get extra hardware for it.

**Comment by tdurand** [comment]
Closing to clean up the issues as seems no one has knowledge to answer you.. feel free to answer yourself if you have figured this out
