### ISSUE TITLE
Question: Does the Datacam work when the camera is moving ?

### ISSUE THREAD

**Issue by abouroubi** [opendatacam/opendatacam#277]
I want to try to install the Jetson Nano and a camera in my car to count the vehicles.
I was wondering if this configuration will work ?

Thank you for your work !

**Comment by vsaw** [comment]
I have never tried it but I can imagine the new Polygon Counter in the development branch should be able to count cars in this setup. 

Additionally you can get the position of the car with the new GPS feature in the development branch.

**Comment by abouroubi** [comment]
Looks promising, thank you for your answer.
