### ISSUE TITLE
Feature: GPS Timestamp in Export

### ISSUE THREAD

**Issue by vsaw** [opendatacam/opendatacam#283]
# Goal

Export the correct time of the counted object where OpenDataCam can not sync system clocks with NTP.

# Background

Timestamps for counted objects use Node.js's `Date` objects which are being synced to the system time. However as Jetson boards don't have a battery powered Real Time Clock (RTC). The system clock needs to be synced via NTP at boot time. In situations where the Jetson does not have internet connection this is not possible. Hence, in those situations the time of the tracked objects is unreliable as it shows arbitrary timestamps and e.g. does not allow to discover the date and time of events.

# Proposed Solution

GPS allows to determine the location and time at location of the device. Therefore, it is proposed to add a new field to the JSON and CSV export containing the GPS time.

## Alternative Solutions

The following alternative solutions have been considered but are regarded as less favorable compared to the proposed solution.

### Run as system service

GPS can be used by NTP as a time source and set the system time accordingly. However this requires GPSD to run as a system service and therefore a deep level of access to the underlying operating system, which is not possible when GPSD is run in a docker container.

### Run GPSD in OpenDataCam Docker Container

We could run GPSD in the same container as OpenDataCam and synchronize the containers date time to GPSD. However this would bloat OpenDataCam as GPS currently is an optional feature and most likely not used by the majority of users.

### Synchronizing node's `Date` with GPS

As I don't know any way to synchronize  node's `Date` objects to GPS time from within node.

**Comment by tdurand** [comment]
merged !
