### ISSUE TITLE
Bug: Counter.JSON and Tracker.JSON should contain recording ID and right file extension

### ISSUE THREAD

**Issue by vsaw** [opendatacam/opendatacam#285]
# Goal

The counter and tracker files in JSON format should contain the recording ID in their fielename and the JSON file extension without the user having to manually rename them.

# Background

All json files are called `counter` or `tracker` without reference to the recording ID or proper file extension. This makes handling them a bit difficult as users do need to rename them manually in order to tell them apart and open them in their favorite JSON file viewer.

# Proposed Solution

OpenDataCam should ensure proper filetype and name as it already does when downloading counter data ins CSV format.

## Alternative Solutions

No alternative solutions have been considered..

**Comment by tdurand** [comment]
merged ;-)
