### ISSUE TITLE
Put multiple videos of a place in a queue

### ISSUE THREAD

**Issue by pekonfuerth** [opendatacam/opendatacam#286]
My camera setup records the video in 1h pieces. Since I have full 24h recordings, that would be 24 video files.
If I put in one file, it goes through it and finishes. When I place the next video in there, I have to reset the counter lines.
Would it be possible to make a queue for files and a checkmark if there should be new counter lines?

**Comment by vsaw** [comment]
Currently OpenDataCam does not have a queue or playlist feature and I don't believe there is one in development. (You'd be welcome to start though :-))

For a workaround you can concatenate the videos before uploading it to OpenDataCam or you could try to use the [gstreamer concat plugin](https://gstreamer.freedesktop.org/documentation/coreelements/concat.html) to concatenate your files before going into Darknet.

**Comment by pekonfuerth** [comment]
pfew, that's way above my skillset :l
Guess I'll just have to concatenate, as you proposed.

**Comment by vsaw** [comment]
Sorry I can't do more for you. If this answers your question, would you mind closing this issue? :-)

**Comment by pekonfuerth** [comment]
Aye, sorry and thanks for your reply 👍
