### ISSUE TITLE
Using RedisJSON 

### ISSUE THREAD

**Issue by collabnix** [opendatacam/opendatacam#296]
Opendatacam uses MongoDB as a backend database. Today Redis comes with Redis Modules like RedisJSON. The RedisJSON module is [open source](https://github.com/RedisJSON/RedisJSON/) & provides in-memory manipulation of JSON documents at high velocity and volume. With RedisJSON, you can natively store document data in a hierarchical, tree-like format to scale and query documents efficiently, significantly improving performance over storing and manipulating JSON with Lua scripts and core Redis data structures.

How complex is it going to be if I use RedisJSON instead of MongoDB?Has anyone tried it before? I am curious to see what kind of improvement it would bring to the table.

**Comment by vsaw** [comment]
As far as I know it has not been tried. If you want to give it a try you would have to modify https://github.com/opendatacam/opendatacam/blob/master/server/db/DBManager.js and replace the Mongo-Connection with Redis. Rest of Opendatacam should work as is if you keep the API in place :-)

**Comment by collabnix** [comment]
@vsaw Let me test it out.

**Comment by tdurand** [comment]
closing this.. in summary generaly open to have different persistence layer connector.. just need to work with the same API DBManager.js if you provide a pull request with an option in the config + the documentation to switch from one or another.
