### ISSUE TITLE
bounding box display

### ISSUE THREAD

**Issue by belarbi2733** [opendatacam/opendatacam#300]
Hello,

Is there any way to remove bounding boxes display but keep in it for counting ?

I don't want to see bounding box that's all

Thanks

**Comment by vsaw** [comment]
Currently there is no setting to display the bounding boxes. You would have to implement it yourself. (Maybe you could also find a work around with Custom CSS overrides in the browser?)

**Comment by tdurand** [comment]
yes, please have a look at the "engines" folder where we draw stuff on the canvas, you can comment out the bbox display if you like : https://github.com/opendatacam/opendatacam/blob/master/components/canvas/engines/LiveViewEngine.js 

No plan to add option for that right now

**Comment by belarbi2733** [comment]
thanks for your help
