### ISSUE TITLE
Develop can not connect to Darknet after Refactoring

### ISSUE THREAD

**Issue by vsaw** [opendatacam/opendatacam#313]
The following lines introduced in https://github.com/opendatacam/opendatacam/pull/312 cause an error that does not allow OpenDatacam to connect to Darknet. (Unless the connection work out at the first try)

https://github.com/opendatacam/opendatacam/blob/fa5fd04c29d6c530eaa2c3d7c51ac4b4a45f0169/server/Opendatacam.js#L851-L853

**Comment by tdurand** [comment]
How exactly can you repro ? maybe @mildsunrise can help ?

**Comment by mildsunrise** [comment]
what's the error message?

**Comment by vsaw** [comment]
The access of `err.code` fails as the parameter is called `e`.

**Comment by mildsunrise** [comment]
*face-palm* sorry, I didn't notice the typo... thanks for the fix

**Comment by tdurand** [comment]
always the case, even if we had 3 x 2 eyes which reviewed this PRs ;-) .. This is were typescript is handy
