### ISSUE TITLE
ANPR Integration

### ISSUE THREAD

**Issue by pigsfoot** [opendatacam/opendatacam#316]
Hi, Sorry not really an issue but i cant find anywhere to ask questions.

Is it possible or has anyone managed to integrate ANPR capture while running Open Data Cam. We are having great success with Open Data Cam counting vehicles but woudl also like to note registration numbers so we can have two cameras and calculate journey time

**Comment by shams3049** [comment]
To my understanding that goes against the principles of this project, it violates the anonymous part.

**Comment by pigsfoot** [comment]
> 
> 
> To my understanding that goes against the principles of this project, it violates the anonymous part.

Not if you mask the license plate and only store hashed version.

**Comment by vsaw** [comment]
There is a very old issue regarding license plates. Is this what you have in mind: https://github.com/opendatacam/opendatacam/issues/63

**Comment by tdurand** [comment]
Yes, please have a look at this issue: https://github.com/opendatacam/opendatacam/issues/63

Currently nothing is beeing develop but open to contributions
