### ISSUE TITLE
Hide bounding boxes

### ISSUE THREAD

**Issue by BarcaBear** [opendatacam/opendatacam#326]
How can you hide only the bounding boxes? It would be nice to have the option of using the ODC bounding boxes or the Deepstream bounding boxes. I know where to enable and disable the Deepstream bounding boxes.

**Comment by tdurand** [comment]
If you want to  hide stuff draw on the canvas on the front-end, you can uncomment some of those draw calls in the CanvasEngine.js : https://github.com/opendatacam/opendatacam/blob/master/components/canvas/CanvasEngine.js#L60

if did sucessfully integrate with Deepstream v5 , any feedback is appreciated here: https://github.com/opendatacam/opendatacam/issues/112
