### ISSUE TITLE
Outsourcing the Database to an external Server

### ISSUE THREAD

**Issue by MaximilianSteverding** [opendatacam/opendatacam#338]
Maybe a feature for the future:

I would like to push the information of a count to a webserver to be able to store the counting information in real-time to an external database. This would enhance the features of ODC as long as the counter is connected to the internet. By pushing the information rather then requesting them the device would not be made into a publicly available webserver so it would be less exposed to attacks.

Is there already the possibility to do a workaround with the existing API that you could hint me to so I could test this?

**Comment by tdurand** [comment]
You can already use an external MongoDB database out of the box, just change the URL in the config.json: https://github.com/opendatacam/opendatacam/blob/master/documentation/CONFIG.md#mongodb-url

If you want to use something else than MongoDB now you need to rewrite the DBManager to fits your needs while keeping the same API : https://github.com/opendatacam/opendatacam/blob/master/server/db/DBManager.js
