### ISSUE TITLE
Trim Opendatacam Docker Image

### ISSUE THREAD

**Issue by vsaw** [opendatacam/opendatacam#369]
The Opendatacam Docker Image seems to be quite large as the `.dockerignore` file seems to not filter out unnecessary things like `.git` or `spec` folders.

We should consider adding things like

```
# Git
.git
.gitignore

# Docker
Dockerfile
docker-compose.yml

# NPM dependencies
node_modules
```

**Comment by vsaw** [comment]
See here for more docker best practices to implement at some point

- https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/
- https://dev.to/nodepractices/docker-best-practices-with-node-js-4ln4

**Comment by vsaw** [comment]
Closed in #370

**Comment by tdurand** [comment]
great work !

I think you leaved your weight file name instead of yolov4 : https://github.com/opendatacam/opendatacam/pull/370/files#diff-58aa082fcc0c51fa7c6e97622a009c2cf69f5e04ee034c8f455b15037698c48cR31

**Comment by vsaw** [comment]
@tdurand good catch!

Please review the fix https://github.com/opendatacam/opendatacam/pull/371

**Comment by tdurand** [comment]
no problem !
