### ISSUE TITLE
Option to add login screen - Question

### ISSUE THREAD

**Issue by zeljkomarinkovic** [opendatacam/opendatacam#385]
I would like to add login screen, on top of ODC

What would be best aproach for doing that, save password somewhere in jetson nano and comapre with login credentials??

**Comment by vsaw** [comment]
ODC runs express JS. So you should be able to use ExpressJS Middleware such as e.g. https://www.npmjs.com/package/express-basic-auth

**Comment by zeljkomarinkovic** [comment]
Thanks, will look into it
