### ISSUE TITLE
inserting connection to mysql db in js code

### ISSUE THREAD

**Issue by MaximilianSteverding** [opendatacam/opendatacam#389]
I want to implement injecting the tracked data of each count at each count to a mysql-database on a remote server. The objective of that is to extract the data in almost real-time to a db that is accessible through the web without exposing the jetson to public access. 

The problem of mine is that i do not know where to best implement the connection statements within the opendatacam js code as well as where exactly the temporary values are passed over to the mongodb as this would be the perfect spot to also inject the values in the mysql table on the remote server.

I am looking forward to your help. Thank you very much!

**Comment by tdurand** [comment]
Hi, 

You should use the development branch for that @vsaw abstracted the interface to the DB, so you should create a MySQLManager.js that implements the DbManagerBase.js functions

Have a look at the MongoDbManager.js https://github.com/opendatacam/opendatacam/blob/development/server/db/MongoDbManager.js

Good luck !
