### ISSUE TITLE
Can this run on mp4?

### ISSUE THREAD

**Issue by cedricve** [opendatacam/opendatacam#411]
Hello we are wondering if this could run directly on mp4 files as well?

Kind regards
Cedric

**Comment by vsaw** [comment]
Yes it can. Simplest way is to "drag n drop" a video file on the web interface. OpenDataCam will restart and start running your file.

**Comment by cedricve** [comment]
that's cool! and is there anyway to send them to an API, and let opencam process it in the background?

**Comment by vsaw** [comment]
Yes. The endpoint is not documented but it's POST to /files

See the implementation in server.js

Rest of the API is documented here https://opendatacam.github.io/opendatacam/apidoc/

**Comment by cedricve** [comment]
Ok cool we might write an article about this for integrating with kerberos.io <http://kerberos.io/> ;)

**Comment by vsaw** [comment]
Great! Drop us a note when it's ready :-)
