### ISSUE TITLE
Run v3.0.2 on real HW

### ISSUE THREAD

**Issue by vsaw** [opendatacam/opendatacam#437]
I can do so for the Jetson Nano.

**Comment by yauh** [comment]
let's go :)

**Comment by vsaw** [comment]
Thank you for testing! I'm building fixing the Darknet dependancy #436 and will release v3.0.2 directly after!

**Comment by vsaw** [comment]
@yauh Beta 2 of v3.0.2 just got released. It should not include any breaking changes as all I did was changing the docker tags for Darknet. But just in case would you mind giving it another try? I would do it myself but I'm currently traveling and do not have any HW with me.

If you're busy just let me know. Then I will merge and hope for the best ;-)

**Comment by yauh** [comment]
Let's risk it. I will be able to test in a couple of days and I have a good feeling about this :)

**Comment by vsaw** [comment]
Here goes nothing! Thank you for your support.

See also https://github.com/opendatacam/opendatacam/releases/tag/v3.0.2
