### ISSUE TITLE
Update development instructions for new github based release process

### ISSUE THREAD

**Issue by vsaw** [opendatacam/opendatacam#440]
Most of the things are now done by a github workflow. We can simplify the release process a lot now!

**Comment by tdurand** [comment]
sounds very cool progress for easier release !! thanks ! 

this week I'm working on v4 , will ping you to avoid breaking stuff

**Comment by vsaw** [comment]
Closed as v3.0.2 is now released.

See also https://github.com/opendatacam/opendatacam/releases/tag/v3.0.2
