### ISSUE TITLE
Get time tracked object in viewable frame

### ISSUE THREAD

**Issue by munsterlander** [opendatacam/opendatacam#463]
So similar to this: https://github.com/opendatacam/opendatacam/issues/413 how would I go about just getting the total time the objects are in the viewable frame?  I know the timestamps are being stored.  My project is to have a camera monitor an intersection and determine how long it takes for the cars to get through the intersection, i.e. determine the average time cars wait.  My plan was to set the camera angle so I have the intersection captured from one angle then move it around throughout the day / weeks to get the aggregate data. 

Normally, I would just querying the mongo db would be sufficient, but I have been instructed to display the real time changing average, so how do I hook into this to start?  Apologies if this is too broad, but I am new to ODC, but not new to developing in a variety of languages.   Thank you for any help you can send my way.

Edit:  I feel like I should be able to just add a new endpoint as I believe I can use the existing Tracker endpoint to get the current recording - if isRecording = true.  That gets the id that I can then just run an aggregation pipeline on Mongo to time difference between the max and min timestamps per object that is a car (or other class).  Then just average that array.    I was thinking with that end point, I could then add a new overlay or such.  Thoughts on this approach?

**Comment by munsterlander** [comment]
I will take a look at this today and see what it contains, but this sounds like it could very well be a solution.  Thank you!  I will report back soon.

**Comment by vsaw** [comment]
The device usually freezes up when Darknet is starting when the power supply is insufficient. As Darknet starts before you see the UI I therefore doubt that this is the case. However it's unusual that you don't have any log output. Can you still SSH into the machine or anything?

**Comment by munsterlander** [comment]
Yes. No issues at all, it just freezes the video.  I can still navigate menus in the ui.  The terminal output still ticks by with the FPS metrics and such.   I am running jetpack 4.5.  Could that be an issue?

**Comment by vsaw** [comment]
You could try connecting to port 8070 from your Browser to see if you still the raw Darknet video feed. If that still works then it's ODCs Video Overlay. If that stopped as well it's Darknet.

JetPack 4.5 should be fine. I use it for development without any issues.

**Comment by munsterlander** [comment]
Ok, so 8070 runs with no issue and keeps dumping JSON to screen (truncated below):

```
[
{
 "frame_id":392, 
 "objects": [ 
  {"class_id":5, "name":"bus", "relative_coordinates":{"center_x":0.506129, "center_y":0.339078, "width":0.091629, "height":0.162073}, "confidence":0.398055}, 
  {"class_id":2, "name":"car", "relative_coordinates":{"center_x":0.644736, "center_y":0.850406, "width":0.156810, "height":0.192310}, "confidence":0.976881}, 
  {"class_id":2, "name":"car", "relative_coordinates":{"center_x":0.380708, "center_y":0.703701, "width":0.112929, "height":0.173237}, "confidence":0.963825}, 
  {"class_id":2, "name":"car", "relative_coordinates":{"center_x":0.841862, "center_y":0.627447, "width":0.147779, "height":0.140140}, "confidence":0.959088}, 
  {"class_id":2, "name":"car", "relative_coordinates":{"center_x":0.648139, "center_y":0.505841, "width":0.083038, "height":0.101927}, "confidence":0.934845}, 
  {"class_id":2, "name":"car", "relative_coordinates":{"center_x":0.486993, "center_y":0.611907, "width":0.105639, "height":0.163455}, "confidence":0.923675}, 
  {"class_id":2, "name":"car", "relative_coordinates":{"center_x":0.222781, "center_y":0.591792, "width":0.087839, "height":0.178671}, "confidence":0.741287}, 
  {"class_id":2, "name":"car", "relative_coordinates":{"center_x":0.570564, "center_y":0.545912, "width":0.069865, "height":0.098347}, "confidence":0.600507}, 
  {"class_id":2, "name":"car", "relative_coordinates":{"center_x":0.547401, "center_y":0.456869, "width":0.057363, "height":0.064715}, "confidence":0.567320}, 
  {"class_id":2, "name":"car", "relative_coordinates":{"center_x":0.361193, "center_y":0.463838, "width":0.054673, "height":0.071001}, "confidence":0.468053}, 
  {"class_id":2, "name":"car", "relative_coordinates":{"center_x":0.426399, "center_y":0.410667, "width":0.053190, "height":0.064270}, "confidence":0.414013}
 ] 
}, 
```

**Comment by vsaw** [comment]
Are you running the browser on the Nano as well?

ODC is using almost all the GPU and CPU of the Nano. So it could be that there is simply not enough CPU left to update the browser. 

I don't know however why Master is not affected by this.🤷‍♂️

**Comment by munsterlander** [comment]
Yes it is all on the Jetson.  So, I ran it on a browser of a different machine.  At first, I got excited because the video was not janky or dropping frames but then it returned.  I then clicked counter and my polygon is restored.  I clicked record and the video froze immediately.  Still not certain what is going on though.  8070 and 8090 keep streaming away, so darknet is still running.  Additionally, I tried to see if it was polygon related and just did a line.  It still froze.  Pathfinder does not though.

I restarted ODC and just let it sit.  After about 1 minute the video overlay just crashed resulting in this:

![image](https://user-images.githubusercontent.com/17042581/139538575-754a2352-8f29-45cd-9141-8c73d3dfdaae.png)

**Comment by munsterlander** [comment]
For this task, I may just switch back to `master` and look at drawing 2 lines and calculating the time between those.  I do love some of the new things I am seeing in `development`.  I also am starting to get a handle on how NextJS is doing components and such. I am new to Next, so I am still sorting out components, but I am able to navigate through everything and I think I am at a point where I can start extending some things.

**Comment by vsaw** [comment]
The grey screen sometimes happens due to changes in MJPEG Proxy. The recording is still running you just don't see the video feed. You could look into the API and query if ODC is still recording. Also I Wonder if this happens in the Docker install as well? (just to exclude any install issues)


Generally the Nano is fine enough.  You can get approx 15-20 fps on the Nano with YoloV4 tiny. The Xavier NX will give you ~60 fps.

**Comment by munsterlander** [comment]
Ok, I will run a docker install later today and see what happens.

**Comment by vsaw** [comment]
@munsterlander Awesome! Congratulations on successfully calculating the wait time. 

I don't have any HW with me so I can not run the Docker images unfortunately. All I can test right now is running OpenDataCam running from source with the Simulated Darknet. This is working properly for me. So who knows what's happening on your machine 🤷‍♂️

Generally speaking are we not accepting any contributions to the `master` branches except for bug-fixes and security issues. Therefore I'd appreciate it a lot if we can get your code running on `development`.

**Comment by munsterlander** [comment]
@vsaw Will do.  I had a teammate of mine try to get `development` going from source on a 2GB nano and he had the same issue.  We can get the video to play, everything works like you expect, until you hit record, then it just freezes.  We plan on working off of `development` because it has a lot of what we want to do, but for now, we are working on `master` to get it going and will incorporate it into `development` once we can figure out what is going on.  Luckily, he is far more knowledgeable about DNN and the native implementations of such.

**Comment by vsaw** [comment]
I know that the 2GB Nano has some RAM limitations and can only run ODC in Headless mode (no Gnome or other GUI running on the device). Maybe that causes the recording to freeze.

**Comment by munsterlander** [comment]
It happens on the 4GB as well though and it happened on a desktop build - which was also weird because it has a GTX 1070 and it was playing the video on super speed saying 247 FPS.  All straight non-docker builds following the wiki instructions from the dev branch.
