### ISSUE TITLE
Disable Next Telemetry

### ISSUE THREAD

**Issue by vsaw** [opendatacam/opendatacam#478]
As pointed out in https://github.com/opendatacam/opendatacam/issues/390#issuecomment-962113092 Next Telemetry seems to be enabled for ODC by default.

We should consider disabling it or issuing a message indicating it is enabled and how to disable it.

**Comment by munsterlander** [comment]
I personally think the default should be disabled and there could be a single line in the docs about how you can enable it if you want to.
