### ISSUE TITLE
Updated tutorial for ODC installation on a Jetson Nano 2GB

### ISSUE THREAD

**Issue by parthapp** [opendatacam/opendatacam#496]
Hello All, I am new to ODC and Linux generally and I am unable to install ODC following the guide on the page dedicated to the Jetson Nano, [here](https://github.com/opendatacam/opendatacam/blob/master/documentation/jetson/JETSON_NANO.md). 

Issue is this: In following the steps exactly, there are errors and warnings and Docker Compose does not install. Googling ways to make it work, I got it installed and ODC running, but I cannot get any CSV or JSON data out of it and the console lists errors continuously. My noob understanding is that ODC and mongodb are not talking to each other, a consequence of copy paste sudo commands from google without any understanding of them. I am using a Jetson Nano 2GB. 

I am requesting that the guide be updated. Thanks a lot and I really appreciate the effort put into this software!

**Comment by vsaw** [comment]
Hey, few remarks here 

1. Can you please provide any logs? Ideally you can provide the docker logs and ODC logs. 
2. The docker-compose install is outdated. Just try the following `sudo apt-get install docker-compose`

Lastly, you're welcome to ask for help at any time, but please remember that this is an Open Source project we maintain in our free time. We ask every member of the community to please respect that, and I believe that "requesting" things is not the right tone for that. Thank you for understanding.

**Comment by parthapp** [comment]
Hello Sir

Thanks for the response.
How do I access ODC logs?

Docker-compose log is below:
sudo docker-compose logs
Attaching to partha_mongo_1, partha_opendatacam_1
opendatacam_1  | mount: /tmp/tmpmount/console: special device /dev/console
does not exist.
opendatacam_1  | umount: /dev: target is busy.
opendatacam_1  | Using video input value from config.json: "file"
opendatacam_1  | Using video input file value from config.json:
"opendatacam_videos/demo.mp4"
opendatacam_1  | Using video input usbcam value from config.json: "v4l2src
device=/dev/video0 ! video/x-raw, framerate=30/1, width=640, height=360 !
videoconvert ! appsink"
opendatacam_1  | Using video input remote_cam value from config.json: "YOUR
IP CAM STREAM (can be .m3u8, MJPEG ...), anything supported by opencv"
opendatacam_1  |
opendatacam_1  | > ***@***.*** start /var/local/opendatacam
opendatacam_1  | > PORT=8080 NODE_ENV=production node server.js
opendatacam_1  |
opendatacam_1  | -----------------------------------
opendatacam_1  | -     Opendatacam initialized     -
opendatacam_1  | - Config loaded:                  -
opendatacam_1  | {
opendatacam_1  |   "OPENDATACAM_VERSION": "3.0.1",
opendatacam_1  |   "PATH_TO_YOLO_DARKNET": "/var/local/darknet",
opendatacam_1  |   "VIDEO_INPUT": "file",
opendatacam_1  |   "NEURAL_NETWORK": "yolov4-tiny",
opendatacam_1  |   "VIDEO_INPUTS_PARAMS": {
opendatacam_1  |     "file": "opendatacam_videos/demo.mp4",
opendatacam_1  |     "usbcam": "v4l2src device=/dev/video0 ! video/x-raw,
framerate=30/1, width=640, height=360 ! videoconvert ! appsink",
opendatacam_1  |     "raspberrycam": "nvarguscamerasrc !
video/x-raw(memory:NVMM),width=1280, height=720, framerate=30/1,
format=NV12 ! nvvidconv ! video/x-raw, format=BGRx, width=640, height=360 !
videoconvert ! video/x-raw, format=BGR ! appsink",
opendatacam_1  |     "remote_cam": "YOUR IP CAM STREAM (can be .m3u8, MJPEG
...), anything supported by opencv",
opendatacam_1  |     "remote_hls_gstreamer": "souphttpsrc location=
http://YOUR_HLSSTREAM_URL_HERE.m3u8 ! hlsdemux ! decodebin ! videoconvert !
videoscale ! appsink"
opendatacam_1  |   },
opendatacam_1  |   "TRACKER_SETTINGS": {
opendatacam_1  |     "objectMaxAreaInPercentageOfFrame": 80,
opendatacam_1  |     "confidence_threshold": 0.2,
opendatacam_1  |     "iouLimit": 0.05,
opendatacam_1  |     "unMatchedFrameTolerance": 5
opendatacam_1  |   },
opendatacam_1  |   "COUNTER_SETTINGS": {
opendatacam_1  |     "minAngleWithCountingLineThreshold": 5,
opendatacam_1  |     "computeTrajectoryBasedOnNbOfPastFrame": 5
opendatacam_1  |   },
opendatacam_1  |   "VALID_CLASSES": [
opendatacam_1  |     "*"
opendatacam_1  |   ],
opendatacam_1  |   "DISPLAY_CLASSES": [
opendatacam_1  |     {
opendatacam_1  |       "class": "bicycle",
opendatacam_1  |       "hexcode": "1F6B2"
opendatacam_1  |     },
opendatacam_1  |     {
opendatacam_1  |       "class": "person",
opendatacam_1  |       "hexcode": "1F6B6"
opendatacam_1  |     },
opendatacam_1  |     {
opendatacam_1  |       "class": "truck",
opendatacam_1  |       "hexcode": "1F69B"
opendatacam_1  |     },
opendatacam_1  |     {
opendatacam_1  |       "class": "motorbike",
opendatacam_1  |       "hexcode": "1F6F5"
opendatacam_1  |     },
opendatacam_1  |     {
opendatacam_1  |       "class": "car",
opendatacam_1  |       "hexcode": "1F697"
opendatacam_1  |     },
opendatacam_1  |     {
opendatacam_1  |       "class": "bus",
opendatacam_1  |       "hexcode": "1F68C"
opendatacam_1  |     }
opendatacam_1  |   ],
opendatacam_1  |   "PATHFINDER_COLORS": [
opendatacam_1  |     "#1f77b4",
opendatacam_1  |     "#ff7f0e",
opendatacam_1  |     "#2ca02c",
opendatacam_1  |     "#d62728",
opendatacam_1  |     "#9467bd",
opendatacam_1  |     "#8c564b",
opendatacam_1  |     "#e377c2",
opendatacam_1  |     "#7f7f7f",
opendatacam_1  |     "#bcbd22",
opendatacam_1  |     "#17becf"
opendatacam_1  |   ],
opendatacam_1  |   "COUNTER_COLORS": {
opendatacam_1  |     "yellow": "#FFE700",
opendatacam_1  |     "turquoise": "#A3FFF4",
opendatacam_1  |     "green": "#a0f17f",
opendatacam_1  |     "purple": "#d070f0",
opendatacam_1  |     "red": "#AB4435"
opendatacam_1  |   },
opendatacam_1  |   "NEURAL_NETWORK_PARAMS": {
opendatacam_1  |     "yolov4": {
opendatacam_1  |       "data": "cfg/coco.data",
opendatacam_1  |       "cfg": "cfg/yolov4-416x416.cfg",
opendatacam_1  |       "weights": "yolov4.weights"
opendatacam_1  |     },
opendatacam_1  |     "yolov4-tiny": {
opendatacam_1  |       "data": "cfg/coco.data",
opendatacam_1  |       "cfg": "cfg/yolov4-tiny.cfg",
opendatacam_1  |       "weights": "yolov4-tiny.weights"
opendatacam_1  |     }
opendatacam_1  |   },
opendatacam_1  |   "TRACKER_ACCURACY_DISPLAY": {
opendatacam_1  |     "nbFrameBuffer": 300,
opendatacam_1  |     "settings": {
opendatacam_1  |       "radius": 3.1,
opendatacam_1  |       "blur": 6.2,
opendatacam_1  |       "step": 0.1,
opendatacam_1  |       "gradient": {
opendatacam_1  |         "1": "red",
opendatacam_1  |         "0.4": "orange"
opendatacam_1  |       },
opendatacam_1  |       "canvasResolutionFactor": 0.1
opendatacam_1  |     }
opendatacam_1  |   },
opendatacam_1  |   "MONGODB_URL": "mongodb://mongo:27017",
opendatacam_1  |   "PORTS": {
opendatacam_1  |     "app": 8080,
opendatacam_1  |     "darknet_json_stream": 8070,
opendatacam_1  |     "darknet_mjpeg_stream": 8090
opendatacam_1  |   }
opendatacam_1  | }
opendatacam_1  | -----------------------------------
opendatacam_1  | Process YOLO initialized
opendatacam_1  | > Ready on http://localhost:8080
opendatacam_1  | > Ready on http://172.18.0.3:8080
opendatacam_1  | Process YOLO started
opendatacam_1  | (node:142) [DEP0001] DeprecationWarning:
OutgoingMessage.flush is deprecated. Use flushHeaders instead.
opendatacam_1  |  CUDA-version: 10000 (10000), cuDNN: 7.6.3, GPU count: 1
opendatacam_1  |  OpenCV version: 4.1.1
opendatacam_1  |  0 : compute_capability = 530, cudnn_half = 0, GPU: NVIDIA
Tegra X1
opendatacam_1  |    layer   filters  size/strd(dil)      input
   output
opendatacam_1  |    0 conv     32       3 x 3/ 2    416 x 416 x   3 ->  208
x 208 x  32 0.075 BF
opendatacam_1  |    1 conv     64       3 x 3/ 2    208 x 208 x  32 ->  104
x 104 x  64 0.399 BF
opendatacam_1  |    2 conv     64       3 x 3/ 1    104 x 104 x  64 ->  104
x 104 x  64 0.797 BF
opendatacam_1  |    3 route  2                                 1/2 ->  104
x 104 x  32
opendatacam_1  |    4 conv     32       3 x 3/ 1    104 x 104 x  32 ->  104
x 104 x  32 0.199 BF
opendatacam_1  |    5 conv     32       3 x 3/ 1    104 x 104 x  32 ->  104
x 104 x  32 0.199 BF
opendatacam_1  |    6 route  5 4                                   ->  104
x 104 x  64
opendatacam_1  |    7 conv     64       1 x 1/ 1    104 x 104 x  64 ->  104
x 104 x  64 0.089 BF
opendatacam_1  |    8 route  2 7                                   ->  104
x 104 x 128
opendatacam_1  |    9 max                2x 2/ 2    104 x 104 x 128 ->   52
x  52 x 128 0.001 BF
opendatacam_1  |   10 conv    128       3 x 3/ 1     52 x  52 x 128 ->   52
x  52 x 128 0.797 BF
opendatacam_1  |   11 route  10                                        1/2
->   52 x  52 x  64
opendatacam_1  |   12 conv     64       3 x 3/ 1     52 x  52 x  64 ->   52
x  52 x  64 0.199 BF
opendatacam_1  |   13 conv     64       3 x 3/ 1     52 x  52 x  64 ->   52
x  52 x  64 0.199 BF
opendatacam_1  |   14 route  13 12                                 ->   52
x  52 x 128
opendatacam_1  |   15 conv    128       1 x 1/ 1     52 x  52 x 128 ->   52
x  52 x 128 0.089 BF
opendatacam_1  |   16 route  10 15                                 ->   52
x  52 x 256
opendatacam_1  |   17 max                2x 2/ 2     52 x  52 x 256 ->   26
x  26 x 256 0.001 BF
opendatacam_1  |   18 conv    256       3 x 3/ 1     26 x  26 x 256 ->   26
x  26 x 256 0.797 BF
opendatacam_1  |   19 route  18                                        1/2
->   26 x  26 x 128
opendatacam_1  |   20 conv    128       3 x 3/ 1     26 x  26 x 128 ->   26
x  26 x 128 0.199 BF
opendatacam_1  |   21 conv    128       3 x 3/ 1     26 x  26 x 128 ->   26
x  26 x 128 0.199 BF
opendatacam_1  |   22 route  21 20                                 ->   26
x  26 x 256
opendatacam_1  |   23 conv    256       1 x 1/ 1     26 x  26 x 256 ->   26
x  26 x 256 0.089 BF
opendatacam_1  |   24 route  18 23                                 ->   26
x  26 x 512
opendatacam_1  |   25 max                2x 2/ 2     26 x  26 x 512 ->   13
x  13 x 512 0.000 BF
opendatacam_1  |   26 conv    512       3 x 3/ 1     13 x  13 x 512 ->   13
x  13 x 512 0.797 BF
opendatacam_1  |   27 conv    256       1 x 1/ 1     13 x  13 x 512 ->   13
x  13 x 256 0.044 BF
opendatacam_1  |   28 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13
x  13 x 512 0.399 BF
opendatacam_1  |   29 conv    255       1 x 1/ 1     13 x  13 x 512 ->   13
x  13 x 255 0.044 BF
opendatacam_1  |   30 yolo
opendatacam_1  | [yolo] params: iou loss: ciou (4), iou_norm: 0.07,
cls_norm: 1.00, scale_x_y: 1.05
opendatacam_1  |   31 route  27
 ->   13 x  13 x 256
opendatacam_1  |   32 conv    128       1 x 1/ 1     13 x  13 x 256 ->   13
x  13 x 128 0.011 BF
opendatacam_1  |   33 upsample                 2x    13 x  13 x 128 ->   26
x  26 x 128
opendatacam_1  |   34 route  33 23                                 ->   26
x  26 x 384
opendatacam_1  |   35 conv    256       3 x 3/ 1     26 x  26 x 384 ->   26
x  26 x 256 1.196 BF
opendatacam_1  |   36 conv    255       1 x 1/ 1     26 x  26 x 256 ->   26
x  26 x 255 0.088 BF
opendatacam_1  |   37 yolo
opendatacam_1  | [yolo] params: iou loss: ciou (4), iou_norm: 0.07,
cls_norm: 1.00, scale_x_y: 1.05
opendatacam_1  | Total BFLOPS 6.910
opendatacam_1  | avg_outputs = 310203
opendatacam_1  |  Allocate additional workspace_size = 26.22 MB
opendatacam_1  | Demo
opendatacam_1  | net.optimized_memory = 0
opendatacam_1  | mini_batch = 1, batch = 1, time_steps = 1, train = 0
opendatacam_1  | nms_kind: greedynms (1), beta = 0.600000
opendatacam_1  | nms_kind: greedynms (1), beta = 0.600000
opendatacam_1  | Loading weights from yolov4-tiny.weights...Done! Loaded 38
layers from weights-file
opendatacam_1  | Got first message from JSONStream
opendatacam_1  | Error with message send by YOLO, not valid JSON
opendatacam_1  | Error with message send by YOLO, not valid JSON
opendatacam_1  | setvideoresolution
opendatacam_1  |
opendatacam_1  |  seen 64, trained: 32012 K-images (500 Kilo-batches_64)
opendatacam_1  | video file: opendatacam_videos/demo.mp4
opendatacam_1  | Video stream: 640 x 360
opendatacam_1  | JSON_sender: new client 27
opendatacam_1  | Error with message send by YOLO, not valid JSON
opendatacam_1  | MJPG_sender: new client 29
opendatacam_1  | (node:142) [DEP0005] DeprecationWarning: Buffer() is
deprecated due to security and usability issues. Please use the
Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
opendatacam_1  | MongoServerSelectionError: getaddrinfo ENOTFOUND mongo
opendatacam_1  |     at Timeout._onTimeout
(/var/local/opendatacam/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
opendatacam_1  |     at listOnTimeout (internal/timers.js:549:17)
opendatacam_1  |     at processTimers (internal/timers.js:492:7) {
opendatacam_1  |   reason: TopologyDescription {
opendatacam_1  |     type: 'Single',
opendatacam_1  |     setName: null,
opendatacam_1  |     maxSetVersion: null,
opendatacam_1  |     maxElectionId: null,
opendatacam_1  |     servers: Map { 'mongo:27017' => [ServerDescription] },
opendatacam_1  |     stale: false,
opendatacam_1  |     compatible: true,
opendatacam_1  |     compatibilityError: null,
opendatacam_1  |     logicalSessionTimeoutMinutes: null,
opendatacam_1  |     heartbeatFrequencyMS: 10000,
opendatacam_1  |     localThresholdMS: 15,
opendatacam_1  |     commonWireVersion: null
opendatacam_1  |   }
opendatacam_1  | }
opendatacam_1  | (node:142) UnhandledPromiseRejectionWarning:
MongoServerSelectionError: getaddrinfo ENOTFOUND mongo
opendatacam_1  |     at Timeout._onTimeout
(/var/local/opendatacam/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
opendatacam_1  |     at listOnTimeout (internal/timers.js:549:17)
opendatacam_1  |     at processTimers (internal/timers.js:492:7)
opendatacam_1  | (node:142) UnhandledPromiseRejectionWarning: Unhandled
promise rejection. This error originated either by throwing inside of an
async function without a catch block, or by rejecting a promise which was
not handled with .catch(). To terminate the node process on unhandled
promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
id: 1)
opendatacam_1  | (node:142) [DEP0018] DeprecationWarning: Unhandled promise
rejections are deprecated. In the future, promise rejections that are not
handled will terminate the Node.js process with a non-zero exit code.
opendatacam_1  | Stream closed.
opendatacam_1  | input video stream closed.
opendatacam_1  | Close socket: out = 0, in = 0
opendatacam_1  | MJPG_sender: close clinet: 0
opendatacam_1  | Close socket: out = 0, in = 0
opendatacam_1  | MJPG_sender: close acceptor: 0
opendatacam_1  |
opendatacam_1  | Close socket: out = 0, in = 0
opendatacam_1  | JSON_sender: close clinet: 0
opendatacam_1  | Close socket: out = 0, in = 0
opendatacam_1  | JSON_sender: close acceptor: 0
opendatacam_1  |
opendatacam_1  | ==== HTTP Stream closed by darknet, reset UI ====
opendatacam_1  | ==== If you are running on a file, it is restarting
 because you reached the end ====
opendatacam_1  | ==== If you are running on a camera, it might have crashed
for some reason and we are trying to restart ====
opendatacam_1  | Stop recording
opendatacam_1  | Restart YOLO
opendatacam_1  |  CUDA-version: 10000 (10000), cuDNN: 7.6.3, GPU count: 1
opendatacam_1  |  OpenCV version: 4.1.1
opendatacam_1  |  0 : compute_capability = 530, cudnn_half = 0, GPU: NVIDIA
Tegra X1
opendatacam_1  |    layer   filters  size/strd(dil)      input
   output
opendatacam_1  |    0 conv     32       3 x 3/ 2    416 x 416 x   3 ->  208
x 208 x  32 0.075 BF
opendatacam_1  |    1 conv     64       3 x 3/ 2    208 x 208 x  32 ->  104
x 104 x  64 0.399 BF
opendatacam_1  |    2 conv     64       3 x 3/ 1    104 x 104 x  64 ->  104
x 104 x  64 0.797 BF
opendatacam_1  |    3 route  2                                 1/2 ->  104
x 104 x  32
opendatacam_1  |    4 conv     32       3 x 3/ 1    104 x 104 x  32 ->  104
x 104 x  32 0.199 BF
opendatacam_1  |    5 conv     32       3 x 3/ 1    104 x 104 x  32 ->  104
x 104 x  32 0.199 BF
opendatacam_1  |    6 route  5 4                                   ->  104
x 104 x  64
opendatacam_1  |    7 conv     64       1 x 1/ 1    104 x 104 x  64 ->  104
x 104 x  64 0.089 BF
opendatacam_1  |    8 route  2 7                                   ->  104
x 104 x 128
opendatacam_1  |    9 max                2x 2/ 2    104 x 104 x 128 ->   52
x  52 x 128 0.001 BF
opendatacam_1  |   10 conv    128       3 x 3/ 1     52 x  52 x 128 ->   52
x  52 x 128 0.797 BF
opendatacam_1  |   11 route  10                                        1/2
->   52 x  52 x  64
opendatacam_1  |   12 conv     64       3 x 3/ 1     52 x  52 x  64 ->   52
x  52 x  64 0.199 BF
opendatacam_1  |   13 conv     64       3 x 3/ 1     52 x  52 x  64 ->   52
x  52 x  64 0.199 BF
opendatacam_1  |   14 route  13 12                                 ->   52
x  52 x 128
opendatacam_1  |   15 conv    128       1 x 1/ 1     52 x  52 x 128 ->   52
x  52 x 128 0.089 BF
opendatacam_1  |   16 route  10 15                                 ->   52
x  52 x 256
opendatacam_1  |   17 max                2x 2/ 2     52 x  52 x 256 ->   26
x  26 x 256 0.001 BF
opendatacam_1  |   18 conv    256       3 x 3/ 1     26 x  26 x 256 ->   26
x  26 x 256 0.797 BF
opendatacam_1  |   19 route  18                                        1/2
->   26 x  26 x 128
opendatacam_1  |   20 conv    128       3 x 3/ 1     26 x  26 x 128 ->   26
x  26 x 128 0.199 BF
opendatacam_1  |   21 conv    128       3 x 3/ 1     26 x  26 x 128 ->   26
x  26 x 128 0.199 BF
opendatacam_1  |   22 route  21 20                                 ->   26
x  26 x 256
opendatacam_1  |   23 conv    256       1 x 1/ 1     26 x  26 x 256 ->   26
x  26 x 256 0.089 BF
opendatacam_1  |   24 route  18 23                                 ->   26
x  26 x 512
opendatacam_1  |   25 max                2x 2/ 2     26 x  26 x 512 ->   13
x  13 x 512 0.000 BF
opendatacam_1  |   26 conv    512       3 x 3/ 1     13 x  13 x 512 ->   13
x  13 x 512 0.797 BF
opendatacam_1  |   27 conv    256       1 x 1/ 1     13 x  13 x 512 ->   13
x  13 x 256 0.044 BF
opendatacam_1  |   28 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13
x  13 x 512 0.399 BF
opendatacam_1  |   29 conv    255       1 x 1/ 1     13 x  13 x 512 ->   13
x  13 x 255 0.044 BF
opendatacam_1  |   30 yolo
opendatacam_1  | [yolo] params: iou loss: ciou (4), iou_norm: 0.07,
cls_norm: 1.00, scale_x_y: 1.05
opendatacam_1  |   31 route  27
 ->   13 x  13 x 256
opendatacam_1  |   32 conv    128       1 x 1/ 1     13 x  13 x 256 ->   13
x  13 x 128 0.011 BF
opendatacam_1  |   33 upsample                 2x    13 x  13 x 128 ->   26
x  26 x 128
opendatacam_1  |   34 route  33 23                                 ->   26
x  26 x 384
opendatacam_1  |   35 conv    256       3 x 3/ 1     26 x  26 x 384 ->   26
x  26 x 256 1.196 BF
opendatacam_1  |   36 conv    255       1 x 1/ 1     26 x  26 x 256 ->   26
x  26 x 255 0.088 BF
opendatacam_1  |   37 yolo
opendatacam_1  | [yolo] params: iou loss: ciou (4), iou_norm: 0.07,
cls_norm: 1.00, scale_x_y: 1.05
opendatacam_1  | Total BFLOPS 6.910
opendatacam_1  | avg_outputs = 310203
opendatacam_1  |  Allocate additional workspace_size = 26.22 MB
opendatacam_1  | Demo
opendatacam_1  | net.optimized_memory = 0
opendatacam_1  | mini_batch = 1, batch = 1, time_steps = 1, train = 0
opendatacam_1  | nms_kind: greedynms (1), beta = 0.600000
opendatacam_1  | nms_kind: greedynms (1), beta = 0.600000
opendatacam_1  | Loading weights from yolov4-tiny.weights...Done! Loaded 38
layers from weights-file
opendatacam_1  | Got first message from JSONStream
opendatacam_1  | Error with message send by YOLO, not valid JSON
opendatacam_1  | setvideoresolution
opendatacam_1  |
opendatacam_1  |  seen 64, trained: 32012 K-images (500 Kilo-batches_64)
opendatacam_1  | video file: opendatacam_videos/demo.mp4
opendatacam_1  | Video stream: 640 x 360
opendatacam_1  | JSON_sender: new client 27
opendatacam_1  | MJPG_sender: new client 29
opendatacam_1  | (node:142) UnhandledPromiseRejectionWarning:
MongoServerSelectionError: getaddrinfo ENOTFOUND mongo
opendatacam_1  |     at Timeout._onTimeout
(/var/local/opendatacam/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
opendatacam_1  |     at listOnTimeout (internal/timers.js:549:17)
opendatacam_1  |     at processTimers (internal/timers.js:492:7)
opendatacam_1  | (node:142) UnhandledPromiseRejectionWarning: Unhandled
promise rejection. This error originated either by throwing inside of an
async function without a catch block, or by rejecting a promise which was
not handled with .catch(). To terminate the node process on unhandled
promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
id: 2)
opendatacam_1  | Ask YOLO to restart to record on a file
opendatacam_1  | Process YOLO restart
opendatacam_1  | Error with message send by YOLO, not valid JSON
opendatacam_1  | problem with request:  Error: read ECONNRESET
opendatacam_1  |     at TCP.onStreamRead
(internal/stream_base_commons.js:205:27) {
opendatacam_1  |   errno: 'ECONNRESET',
opendatacam_1  |   code: 'ECONNRESET',
opendatacam_1  |   syscall: 'read'
opendatacam_1  | }
opendatacam_1  | Something went wrong: read ECONNRESET
opendatacam_1  | Too much retries, YOLO took more than 3 min to start,
likely an error
opendatacam_1  | 6000
opendatacam_1  | ==== HTTP Stream closed by darknet, reset UI ====
opendatacam_1  | ==== If you are running on a file, it is restarting
 because you reached the end ====
opendatacam_1  | ==== If you are running on a camera, it might have crashed
for some reason and we are trying to restart ====
opendatacam_1  | Stop recording
opendatacam_1  | Process YOLO exit
opendatacam_1  | Process YOLO stopped
opendatacam_1  | Process YOLO started
opendatacam_1  |  CUDA-version: 10000 (10000), cuDNN: 7.6.3, GPU count: 1
opendatacam_1  |  OpenCV version: 4.1.1
opendatacam_1  |  0 : compute_capability = 530, cudnn_half = 0, GPU: NVIDIA
Tegra X1
opendatacam_1  |    layer   filters  size/strd(dil)      input
   output
opendatacam_1  |    0 conv     32       3 x 3/ 2    416 x 416 x   3 ->  208
x 208 x  32 0.075 BF
opendatacam_1  |    1 conv     64       3 x 3/ 2    208 x 208 x  32 ->  104
x 104 x  64 0.399 BF
opendatacam_1  |    2 conv     64       3 x 3/ 1    104 x 104 x  64 ->  104
x 104 x  64 0.797 BF
opendatacam_1  |    3 route  2                                 1/2 ->  104
x 104 x  32
opendatacam_1  |    4 conv     32       3 x 3/ 1    104 x 104 x  32 ->  104
x 104 x  32 0.199 BF
opendatacam_1  |    5 conv     32       3 x 3/ 1    104 x 104 x  32 ->  104
x 104 x  32 0.199 BF
opendatacam_1  |    6 route  5 4                                   ->  104
x 104 x  64
opendatacam_1  |    7 conv     64       1 x 1/ 1    104 x 104 x  64 ->  104
x 104 x  64 0.089 BF
opendatacam_1  |    8 route  2 7                                   ->  104
x 104 x 128
opendatacam_1  |    9 max                2x 2/ 2    104 x 104 x 128 ->   52
x  52 x 128 0.001 BF
opendatacam_1  |   10 conv    128       3 x 3/ 1     52 x  52 x 128 ->   52
x  52 x 128 0.797 BF
opendatacam_1  |   11 route  10                                        1/2
->   52 x  52 x  64
opendatacam_1  |   12 conv     64       3 x 3/ 1     52 x  52 x  64 ->   52
x  52 x  64 0.199 BF
opendatacam_1  |   13 conv     64       3 x 3/ 1     52 x  52 x  64 ->   52
x  52 x  64 0.199 BF
opendatacam_1  |   14 route  13 12                                 ->   52
x  52 x 128
opendatacam_1  |   15 conv    128       1 x 1/ 1     52 x  52 x 128 ->   52
x  52 x 128 0.089 BF
opendatacam_1  |   16 route  10 15                                 ->   52
x  52 x 256
opendatacam_1  |   17 max                2x 2/ 2     52 x  52 x 256 ->   26
x  26 x 256 0.001 BF
opendatacam_1  |   18 conv    256       3 x 3/ 1     26 x  26 x 256 ->   26
x  26 x 256 0.797 BF
opendatacam_1  |   19 route  18                                        1/2
->   26 x  26 x 128
opendatacam_1  |   20 conv    128       3 x 3/ 1     26 x  26 x 128 ->   26
x  26 x 128 0.199 BF
opendatacam_1  |   21 conv    128       3 x 3/ 1     26 x  26 x 128 ->   26
x  26 x 128 0.199 BF
opendatacam_1  |   22 route  21 20                                 ->   26
x  26 x 256
opendatacam_1  |   23 conv    256       1 x 1/ 1     26 x  26 x 256 ->   26
x  26 x 256 0.089 BF
opendatacam_1  |   24 route  18 23                                 ->   26
x  26 x 512
opendatacam_1  |   25 max                2x 2/ 2     26 x  26 x 512 ->   13
x  13 x 512 0.000 BF
opendatacam_1  |   26 conv    512       3 x 3/ 1     13 x  13 x 512 ->   13
x  13 x 512 0.797 BF
opendatacam_1  |   27 conv    256       1 x 1/ 1     13 x  13 x 512 ->   13
x  13 x 256 0.044 BF
opendatacam_1  |   28 conv    512       3 x 3/ 1     13 x  13 x 256 ->   13
x  13 x 512 0.399 BF
opendatacam_1  |   29 conv    255       1 x 1/ 1     13 x  13 x 512 ->   13
x  13 x 255 0.044 BF
opendatacam_1  |   30 yolo
opendatacam_1  | [yolo] params: iou loss: ciou (4), iou_norm: 0.07,
cls_norm: 1.00, scale_x_y: 1.05
opendatacam_1  |   31 route  27
 ->   13 x  13 x 256
opendatacam_1  |   32 conv    128       1 x 1/ 1     13 x  13 x 256 ->   13
x  13 x 128 0.011 BF
opendatacam_1  |   33 upsample                 2x    13 x  13 x 128 ->   26
x  26 x 128
opendatacam_1  |   34 route  33 23                                 ->   26
x  26 x 384
opendatacam_1  |   35 conv    256       3 x 3/ 1     26 x  26 x 384 ->   26
x  26 x 256 1.196 BF
opendatacam_1  |   36 conv    255       1 x 1/ 1     26 x  26 x 256 ->   26
x  26 x 255 0.088 BF
opendatacam_1  |   37 yolo
opendatacam_1  | [yolo] params: iou loss: ciou (4), iou_norm: 0.07,
cls_norm: 1.00, scale_x_y: 1.05
opendatacam_1  | Total BFLOPS 6.910
opendatacam_1  | avg_outputs = 310203
opendatacam_1  |  Allocate additional workspace_size = 26.22 MB
opendatacam_1  | Demo
opendatacam_1  | net.optimized_memory = 0
opendatacam_1  | mini_batch = 1, batch = 1, time_steps = 1, train = 0
opendatacam_1  | nms_kind: greedynms (1), beta = 0.600000
opendatacam_1  | nms_kind: greedynms (1), beta = 0.600000
opendatacam_1  | Loading weights from yolov4-tiny.weights...Done! Loaded 38
layers from weights-file
opendatacam_1  | Got first message from JSONStream
opendatacam_1  | Error with message send by YOLO, not valid JSON
opendatacam_1  | setvideoresolution
opendatacam_1  |
opendatacam_1  |  seen 64, trained: 32012 K-images (500 Kilo-batches_64)
opendatacam_1  | video file: opendatacam_videos/demo.mp4
opendatacam_1  | Video stream: 640 x 360
opendatacam_1  | JSON_sender: new client 27
opendatacam_1  | Start recording
opendatacam_1  | MJPG_sender: new client 29
opendatacam_1  | Stop recording
opendatacam_1  | (node:142) UnhandledPromiseRejectionWarning:
MongoServerSelectionError: getaddrinfo ENOTFOUND mongo
opendatacam_1  |     at Timeout._onTimeout
(/var/local/opendatacam/node_modules/mongodb/lib/core/sdam/topology.js:430:30)
opendatacam_1  |     at listOnTimeout (internal/timers.js:549:17)
opendatacam_1  |     at processTimers (internal/timers.js:492:7)
opendatacam_1  | (node:142) UnhandledPromiseRejectionWarning: Unhandled
promise rejection. This error originated either by throwing inside of an
async function without a catch block, or by rejecting a promise which was
not handled with .catch(). To terminate the node process on unhandled
promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
id: 3)

**Comment by munsterlander** [comment]
If I were you, I would wipe the install and just follow the instructions here:  https://github.com/opendatacam/opendatacam#2-install-and-start-opendatacam-  It downloads a script that installs everything for you.

**Comment by parthapp** [comment]
Hello Sir. That is the link I started with and it was working perfectly
till 11/05. Since evening 11/06, that script has not worked for me. An
observation: the balena version of ODC uses mongodb 4.2.x and I noticed
that my docker had mongo "latest" installed. I have tried and failed to
install an older mongodb. I will try the script again and confirm if it
works now with 4.3.
Thanks again for your help. Really appreciate it.

**Comment by vsaw** [comment]
This was because I accidentally reverted the master branch to v3.0.1 which contains outdated installation instructions.

I will revert master back to v3.0.2 when I get the chance. In the mean time please download and view v3.0.2 manually via the GitHub release page.
