### ISSUE TITLE
Running on GCP VM

### ISSUE THREAD

**Issue by yasirderq** [opendatacam/opendatacam#575]
Hi I setup opendatacam on a virtual machine and I am able to see the video stream and  detection json stream via reverse proxy but for the app I get 500| Internal server error. 

Default port mapping is 8080:8080 8070:8070 and 8090:8090, I tried changing it to 8008:8080 but that didn't help. darknet streams are working fine but not sure what needs to be done for the app to work on my local machine. 

It will be great if someone can help in this regard.

**Comment by vsaw** [comment]
Hey @yasirderq sorry for the long pause. Could you share some logs to help me pin point the issue.

**Comment by vsaw** [comment]
Closed due to inactivity
