### ISSUE TITLE
MongoDB persistTracker=false setting not applied by OpenDatacam

### ISSUE THREAD

**Issue by effort10** [opendatacam/opendatacam#584]
Hi,

It seems that Opendatacam is not applying the persistTracker:false (config.json) on the development branch installation.
I am still getting records being written to the mongodb tracker collection for some reason.

Has anybody else noticed this issue.

Thanks

![image](https://user-images.githubusercontent.com/48510263/227763038-04046a65-f9d8-4c54-8aa5-b433ec2c2a28.png)

**Comment by vsaw** [comment]
I quickly skimmed through the code and it should still work. Are you running development from source or one of the docker images?

And just to make sure the rest of the config works? So I you make changes they get accepted?

**Comment by effort10** [comment]
Hi. We ran git clone from git clone --branch development https://github.com/opendatacam/opendatacam.git
and then installed it via install-opendatacam.sh, yes it was a docker install, should i rather do non-docker?

Thank you

**Comment by vsaw** [comment]
Ah that explains it. The standard docker-compose.yml files always point to the latest non-development release!

Just edit them and replace the docker tag, this should then pull the correct docker image!

**Comment by effort10** [comment]
Hi,

Makes sense, thank you, i will try that.

Regards
