### ISSUE TITLE
Saving counter locations and names

### ISSUE THREAD

**Issue by TychoML** [opendatacam/opendatacam#588]
Is there a way to save the locations and names of counter lines or polygon areas, such that they can be reloaded for future use? I use the same opendatacam installation for multiple videos, and being able to save and restore the counter settings would greatly improve the ease of use.

**Comment by maddust** [comment]
@TychoML on the bottom left corner there is two arrows . This allows you to download or upload lines configurations and names to be re-used .

This should resolve your issue .

Hope it helps .

**Comment by TychoML** [comment]
@maddust Thanks a lot, I totally missed that. It works wonderfully!
