### ISSUE TITLE
General Project Documentation 

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam#76]
Available as a website here: https://opendatacam.github.io/opendatacam/ thanks to github pages

### Remaining task

- [x] Replace screencast picture ?
- [x] Link to housing.md documentation
- [x] Add Open Graph Images for opendatacam repo : https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/
- [x] Proof read documentation
- [x] Add screenshot of how to add wifi password in WIFI_HOTSPOT_SETUP.md
- [x] Work on a simple technical architecture diagram 
- [x] Rework links on the markdown file to have github pages linking working: https://github.blog/2016-12-05-relative-links-for-github-pages/

### Original post

We start to have several markdown files:

- https://github.com/moovel/lab-opendatacam/blob/v2/doc/CONFIG.md
- https://github.com/moovel/lab-opendatacam/blob/v2/doc/CREATE_DOCKER_IMAGE.md
- https://github.com/moovel/lab-opendatacam/blob/v2/doc/FLASH_JETSON.md
- https://github.com/moovel/lab-opendatacam/blob/v2/doc/RUN_WITHOUT_DOCKER.md
- TODO one on architecture

Should we use the Wiki tab of github ? In my experience it is nice to have the contextual menu

Another way to go would be to generate a website from markdown file like with  something like read the doc : https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html  ... But not sure we want this.

Let's see as we add more stuff to the README is some change is needed

**Comment by b-g** [comment]
Hi @tdurand, True! Either way is fine. I personally would favor simply to have a TOC in the README listing the topics and linking to the other files. That way everything incl. the tocs is nicely contained in our repo. The wiki tab feels at least for the slightly disconnected.

**Comment by tdurand** [comment]
Yes, for now will just work on content, and when we have all the content let's see what makes sense.

**Comment by tdurand** [comment]
- [ ] Work on a CODEOFCONDUCT.md section

**Comment by tdurand** [comment]
- [ ] Work on a CODEOFCONDUCT.md section
- [ ] Add a LICENCE , ping @b-g

**Comment by tdurand** [comment]
- [ ] Work on a CODEOFCONDUCT.md section
- [ ] Add a LICENCE.md
- [ ] Work on a simple technical architecture diagram

**Comment by tdurand** [comment]
cc @b-g , first shot at a general technical architecture schema.. Feel free to edit here: https://docs.google.com/drawings/d/1ew5ux-wcMdxqHVwois21zYpXn63UNfM0r48wZcCl84o/edit?usp=sharing

![Technical Architecture Opendatacam v2](https://user-images.githubusercontent.com/533590/60488614-afd33400-9ca2-11e9-9c00-4b7a54f5a4e2.png)

**Comment by tdurand** [comment]
Also assigned you for Ethics + Licence + Proof read (see first post of this thread)

**Comment by tdurand** [comment]
See this other tool to generate a website from technical doc: https://www.docsy.dev/  (by Google) , with https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html these would be too ways to improve our technical doc experience as we grow them in the future. _(for example many place in the doc I would like to repeat something or do a condition to make it more digest, but with raw markdown I can't)_

**Comment by shams3049** [comment]
I personally thing the user device tobe just be a remote control, access and storage point, sort of conveys the true potential for this application. 

https://purepng.com/photo/25166/clipart-dedicated-server
