### ISSUE TITLE
Document how to run without jetson

### ISSUE THREAD

**Issue by kevinjosue2326** [opendatacam/opendatacam#92]
I would like to know if I can install it on a computer other than tx2 or nano, I have ubuntu 18.04 and GPU: RTX Titan 2080 TI. Cuda 10.0, and the specifications that a document in the document as Cudnn 7.3. and tensorRT 5.0, my question is is it possible to run it on a computer with my specifications and if so, what steps would I have to follow because of the architecture and the configurations that are in the repository? They are for another architecture.

My processor is I9-9900K Intel.
Ram: 64 GB.
GPU: RTX TITAN 2080TI

**Comment by tdurand** [comment]
Yes it is possible:

- with docker-nvidia , I need to finish the documentation on this and publish a docker image: https://github.com/opendatacam/opendatacam/blob/master/documentation/DOCKER_CLOUDANDDESKTOP.md

- without docker, you need to install all dependencies yourself, and also this is not documented properly yet but it will be something similar to https://github.com/opendatacam/opendatacam/blob/master/documentation/RUN_WITHOUT_DOCKER.md

It is on my todo list for this week to document this, I'll ping you once it is done

**Comment by tdurand** [comment]
Some more context on this https://github.com/opendatacam/opendatacam/issues/64

**Comment by tdurand** [comment]
It will close this one in favor of #64 , just subscribe to the other one to be updated when ready.
