### ISSUE TITLE
PoseNet 2.0 with TensorFlow.js

### ISSUE THREAD

**Issue by b-g** [opendatacam/opendatacam#93]
> We just released PoseNet 2.0 with TensorFlow.js, including a much more accurate ResNet-based model!

https://twitter.com/TensorFlow/status/1142111597344821248

**Comment by shams3049** [comment]
Is it possible to do transfer learning? from the current models in YOLO to Posenet 2.0!!

**Comment by b-g** [comment]
No I don't think so ... but one idea could be to make the detection framework e.g. YOLO configurable with a few prepared and selected ones like Posenet.

**Comment by tdurand** [comment]
@b-g great, they don't tell much about the status of the node.js - gpu  but I guess in a few months it will be much better.

And in the browser with webgl it is very impressive

**Comment by tdurand** [comment]
Closing this one to clean up and keeping: https://github.com/opendatacam/opendatacam/issues/71
