### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam#96]
**Features**

- [x] Add download logs on the console / init screen 
- [ ] info/help/warning dialogs a bit annoying … maybe add flag ‘understood’ like in Photoshop?
- [x] Add Opendatacam version in the UI
- [x] Fix title in menu to OpenDataCam
- [x] Fix bbox labels to just show the type / percentage in the Liveview if the width is too small they are overlapping each other

**Low level:**

- [ ]  Data view screen: Optimize perfs (currently re-render every tick) + only render current recording if page = 0
- [ ]  Android chrome: bug when returning from input entry, canvas doesn't re-render correctly (going from a tab to another solves it)... Also seems stream out of sync but maybe because of wifi connexion... Maybe add fulllscreen mode
- [ ] Safari mobile on iPhone SE: bug with innerHeight and height: 100% not consistent.. try to make something more robust
- [ ] Add routing with URLs to be able to use back button

**Comment by tdurand** [comment]
FYI I just added a download logs button @b-g 😎 , very good suggestion

**Comment by llobiancoale** [comment]
Hi i would like to see an option to resize the video/stream (if it isnt already there) 
And an (auto)restart Funktion if it has connection Problems with an ipcam

**Comment by tdurand** [comment]
adding to v4 , will consider this issue as a "fix it or close it" one 😄

**Comment by vsaw** [comment]
Won't fix for now. Have not received many requests/complaints about this.
